name: Build and Push Image

on:
  push:
    branches:
      - 'main'
    paths:
      - '!README.md'
      - '!LICENSE'

  pull_request:
    paths:
      - '!README.md'
      - '!LICENSE'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: NOMAD_VERSION=1.1.4
          tags: kholisrag/nomad:latest,kholisrag/nomad:1.1.4
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true